// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrKSU5V9Dlh_6BGRdtddiH7_2Nx9skVNg',
    appId: '1:290757203963:web:56c30867be4cc0f1b0dd5e',
    messagingSenderId: '290757203963',
    projectId: 'test-login1-db7eb',
    authDomain: 'test-login1-db7eb.firebaseapp.com',
    storageBucket: 'test-login1-db7eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7OySH1EV1488COqZjN7LQd1pGEhdqK04',
    appId: '1:290757203963:android:b66e0b20907e556cb0dd5e',
    messagingSenderId: '290757203963',
    projectId: 'test-login1-db7eb',
    storageBucket: 'test-login1-db7eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWm9GdW_9utga65Ky-y-4y1hB6Xkyr6zA',
    appId: '1:290757203963:ios:33fd5631334862f0b0dd5e',
    messagingSenderId: '290757203963',
    projectId: 'test-login1-db7eb',
    storageBucket: 'test-login1-db7eb.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWm9GdW_9utga65Ky-y-4y1hB6Xkyr6zA',
    appId: '1:290757203963:ios:33fd5631334862f0b0dd5e',
    messagingSenderId: '290757203963',
    projectId: 'test-login1-db7eb',
    storageBucket: 'test-login1-db7eb.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrKSU5V9Dlh_6BGRdtddiH7_2Nx9skVNg',
    appId: '1:290757203963:web:668a0120ad7a11ceb0dd5e',
    messagingSenderId: '290757203963',
    projectId: 'test-login1-db7eb',
    authDomain: 'test-login1-db7eb.firebaseapp.com',
    storageBucket: 'test-login1-db7eb.firebasestorage.app',
  );

}